# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./ICallback.h \
    ./icallback_global.h \
    ./IShapeBuilder.h \
    ./IShapeEditor.h
SOURCES += ./ICallback.cpp
