# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./facetool.h \
    ./TwoPointsShapeBuilder.h \
    ./ConsecutiveBuilder.h \
    ./PolyBuilder.h \
    ./ShapeBuilderBase.h \
    ./shapeBuilders_global.h \
    ./TextBuilder.h
SOURCES += ./facetool.cpp \
    ./ShapeBuilderBase.cpp \
    ./TextBuilder.cpp
TRANSLATIONS += ./shapebuilders_zh.ts
