# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./CallBack.h \
    ./drawareawidget.h \
    ./mainwindow.h \
    ./scroll.h \
    ./stable.h \
    ./dataserver.h
SOURCES += ./CallBack.cpp \
    ./dataserver.cpp \
    ./drawareawidget.cpp \
    ./main.cpp \
    ./mainwindow.cpp \
    ./scroll.cpp
FORMS += ./mainwindow.ui
TRANSLATIONS += ./draw_zh_cn.ts
